name: Run tests on Linux

on: 
    push:
    workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
            python-version: "3.12"

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.34.1/allure-2.34.1.tgz
          tar -zxvf allure-2.34.1.tgz
          sudo mv allure-2.34.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      - name: Install dependencies
        run: |
            pip install selenium
            pip install pytest
            pip install allure-pytest
      
      - name: Run tests with Allure
        run: pytest -s --alluredir=allure-results
    
      - name: Generate Allure report
        if: always()
        run: allure generate allure-results -o allure-report --clean
      
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
      
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-pages-artifact@v4
        with:
          path: allure-report

  deploy:
    needs: test
    if: always()

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy Allure Report to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

