name: Run tests on Linux

on: 
    push:
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
            python-version: "3.12"
    
      - name: Install dependencies
        run: |
            pip install selenium
            pip install pytest
      
      - name: Run tests with Pytest
        run: pytest -s